# Don't forget to rebuild and start the elasticsearch image after changing this file:
#     $ ./scripts/docker rebuild elasticsearch
#     $ ./scripts/docker up -d elasticsearch

network.host: 0.0.0.0
http.port: 9200

# dev-only setting to allow client-side ES front-ends
http.cors.allow-origin: "*"
http.cors.enabled: true
index.max_result_window: 1000000

- # Eventually we want to enable this option, but currently it causes ES
- # timeouts due to tests referencing non-existent indices. For example,
- # saving a user triggers an async task that updates ES, and that fails
- # if the index does not exist. Many tests create and save users but few
- # do explicit ES index creation as is conventional for tests that
- # interact with ES.
- #action.auto_create_index: false
