# Base env containing default values which get
# overridden or added to in each of the specific envs below.
---
base:
  sudo_user: cchq
  django_bind: 0.0.0.0
  django_port: 9010
  flower_port: 5555
  should_migrate: False
  home: "/home/cchq"
  project: commcare-hq
  code_repo: 'git://github.com/dimagi/commcare-hq.git'
  timing_log: null  # make a file path to log deploy timing to it. e.g. '../fabric-timing.txt'

  # list of servers where the NewRelic app agent should be running
  new_relic_enabled: []
  
development:
  should_migrate: True

  # parameters for configuring the celery worker processes
  celery_processes:
    '*':
      main:
        concurrency: 1
      background_queue:
        concurrency: 1
      periodic:
        concurrency: 1
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 1
      reminder_queue:
        concurrency: 1
      reminder_rule_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 1
      sms_queue:
        concurrency: 1
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      flower: {}

india:
  environment: india
  should_migrate: True

  celery_processes:
    '*':
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
      flower: {}

preview:
  environment: preview
  code_branch: master
  flower_port: 5556
  django_port: 7999

production:
  environment: production
  should_migrate: True

  new_relic_enabled:
    - hqdjango3.internal.commcarehq.org
    - hqdjango4.internal.commcarehq.org
    - hqdjango5.internal.commcarehq.org
    - hqcelery1.internal.commcarehq.org
    - hqcelery0.internal.commcarehq.org

  celery_processes:
    hqcelery0:
      main:
        concurrency: 8
      background_queue:
        concurrency: 4
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      email_queue:
        concurrency: 2
    hqcelery1:
      reminder_queue:
        concurrency: 8
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 8
      ucr_queue:
        concurrency: 4
      flower: {}

staging:
  environment: staging
  should_migrate: True

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      pillow_retry_queue:
        concurrency: 1
      saved_exports_queue:
        concurrency: 3
      ucr_queue:
        concurrency: 1
      email_queue:
        concurrency: 1
      flower: {}

zambia:
  environment: production
  should_migrate: True

  celery_processes:
    '*':
      main:
        concurrency: 4
      background_queue:
        concurrency: 2
      periodic:
        concurrency: 4
      pillow_retry_queue:
        concurrency: 1
      reminder_case_update_queue:
        concurrency: 4
      reminder_queue:
        concurrency: 4
      reminder_rule_queue:
        concurrency: 4
      saved_exports_queue:
        concurrency: 3
      sms_queue:
        concurrency: 4
      ucr_queue:
        concurrency: 2
      email_queue:
        concurrency: 2
      flower: {}
