web:
  build: ../
  dockerfile: ./docker/Dockerfile_commcarehq
  working_dir: /mnt
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - ../:/mnt
    - ${DOCKER_DATA_HOME}/sharedfiles:/sharedfiles
  ports:
    - "8000:8000"
  environment:
    PYTHONUSERBASE: /vendor
    CUSTOMSETTINGS: "docker.localsettings-docker"  
  external_links:
    - hqservice_postgres_1:postgres
    - hqservice_couch_1:couch
    - hqservice_redis_1:redis
    - hqservice_elasticsearch_1:elasticsearch
