# Service configurations specific to 'arm64' (Apple M1) architecture for MacOS Big Sur (v 11).

version: '2.3'

services:
  postgres:
    # TODO: enumerate differences with 'dimagi/docker-postgresql' image
    image: docker.io/arm64v8/postgres
