version: '2.3'

services:
  citus_master:
    image: 'citusdata/citus:8.1.1'
    ports: ["${CITUS_MASTER_EXTERNAL_PORT:-5600}:5432"]
    labels: ['com.citusdata.role=Master']
    volumes:
      - ${VOLUME_PREFIX}citus_master:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: commcare_ucr_citus
      POSTGRES_USER: commcarehq
      POSTGRES_PASSWORD: commcarehq
  citus_manager:
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { citus_master: { condition: service_healthy } }
    environment:
      CITUS_HOST: citus_master
      POSTGRES_DB: commcare_ucr_citus
      POSTGRES_USER: commcarehq
      POSTGRES_PASSWORD: commcarehq
  citus_worker1:
    image: 'citusdata/citus:8.1.1'
    ports: ["${CITUS_WORKER1_EXTERNAL_PORT:-5601}:5432"]
    labels: ['com.citusdata.role=Worker']
    depends_on: { citus_manager: { condition: service_healthy } }
    volumes:
      - ${VOLUME_PREFIX}citus_worker1:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: commcare_ucr_citus
      POSTGRES_USER: commcarehq
  citus_worker2:
    image: 'citusdata/citus:8.1.1'
    ports: ["${CITUS_WORKER2_EXTERNAL_PORT:-5602}:5432"]
    labels: ['com.citusdata.role=Worker']
    depends_on: { citus_manager: { condition: service_healthy } }
    volumes:
      - ${VOLUME_PREFIX}citus_worker2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: commcare_ucr_citus
      POSTGRES_USER: commcarehq
