- id: name
  name: Name
  description: ""
  default: ""
  type: hq
  widget: text

- id: application_version
  name: "App Version"
  description: ""
  values: ["1.0", "2.0"]
  value_names: ["1.x", "2.x"]
  default: "2.0"
  disabled: true
  disabled_txt: "We suggest moving to CommCare 2.0 and above, unless your project is using referrals"

- id: build_spec
  name: "CommCare Version"
  description: 'We frequently release new versions of CommCare Mobile. Use the latest version to take advantage of new features and bug fixes. Note that if you are using CommCare for Android you must also update your version of CommCare from the Google Play Store.'
  widget: build_spec
  # this depends on builds are available, and on application_version
  # values, value_names, and default are magically set elsewhere
  # the build_spec widget depends on application_version coming before it in
  # this file

- id: platform
  name: "Java Phone Platform"
  values: ['nokia/s40', 'nokia/s60', 'winmo', 'generic']
  value_names: ['Nokia S40 (default)', 'Nokia S60', 'WinMo', 'Generic']
  default: 'nokia/s40'

- id: text_input
  name: "Text Input"
  widget: text_input
  values: ['roman', 'native', 'custom-keys', 'qwerty']
  value_names: [Roman, Native (International), Custom Keys, Full Keyboard]
  default: roman
  since: {qwerty: '2.6', 'custom-keys': '1.3'}
  requires: "{hq.platform}='nokia/s40'||{hq.platform}='nokia/s60'"

# RemoteApp Only
- id: profile_url
  name: "Profile URL"
  requires: "{$parent.doc_type}='RemoteApp'"
  hide_if_not_enabled: true
  widget: text

- id: manage_urls
  name: "Auto-manage URLs"
  requires: "{$parent.doc_type}='RemoteApp'"
  hide_if_not_enabled: true
  widget: bool
  default: false


# Application only
- id: custom_base_url
  name: "Custom Base URL"
  description: 'Use a different base URL for all app URLs. This makes the phone send forms, sync and look for updates from a differnent URL. Main use case is to allow migrating ICDS to a new cluster.'
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  widget: text
  toggle: CUSTOM_APP_BASE_URL

- id: case_sharing
  name: "Case Sharing"
  description: 'Allow mobile workers in the same case sharing group to share case lists.  Read more on the <a href="https://confluence.dimagi.com/display/commcarepublic/Case+Sharing"/>Help Site</a>'
  description_format: html
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  since: "2.0"

- id: cloudcare_enabled
  name: "CloudCare"
  description: 'Allow mobile workers to access the web-based version of your application. Read more on the <a href="https://confluence.dimagi.com/display/commcarepublic/Using+CloudCare"/>Help Site</a>'
  description_format: html
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  since: "2.0"
  permission: "cloudcare"

- id: commtrack_requisition_mode
  name: "CommCare Supply Requisition Mode"
  description: "CommCare Supply Requisition Mode"
  description_format: html
  requires: "{$parent.commtrack_enabled}=true"
  values: ['disabled', '3-step', '4-step']
  value_names:
   - "Disable Requisitions"
   - "3 Step Requisitions (Requisition -> Fulfillment -> Receipt)"
   - "4 Step Requisitions (Requisition -> Approval -> Fulfillment -> Receipt)"
  hide_if_not_enabled: true
  preview: true
  since: "2.0"

- id: use_custom_suite
  name: "Custom Suite File"
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  disabled: true

- id: custom_suite
  name: "Custom Suite"
  widget: textarea
  requires: "{$parent.doc_type}='Application'"
  disabled: true

- id: admin_password
  name: "Admin Password"
  widget: password
  hide_if_not_enabled: true

- id: secure_submissions
  name: "Use Secure Submissions"
  widget: bool
  default: false
  since: '2.8'
  preview: true

- id: translation_strategy
  name: 'Translations Strategy'
  values: ['dump-known', 'select-known', 'simple']
  value_names:
   - 'Version 1 translations (old)'
   - 'Version 2 translations (recommended)'
   - 'Simple (FOR TESTING ONLY: crashes with any unrecognized user-defined translations)'
  default: 'select-known'
  requires: "{$parent.doc_type}='Application'"
  preview: true
  disabled: true
  disabled_txt: Oops! This setting has been discontinued. We recommend you change this setting to Version 2, and it will no longer appear on your settings page.

- id: auto_gps_capture
  name: 'Auto Capture Location<br />(all forms)'
  description: >
    On CommCare Android, have this form automatically capture the user's current geo-location.
  widget: bool
  default: false
  since: '2.14'

- id: amplifies_workers
  name: 'Service Delivery App'
  description: "This application is used for service delivery. Examples: An FLW who uses CommCare to improve counseling and screening of pregnant women. An FLW that uses CommCare Supply to improve their supply of medicines. A teacher who uses CommCare to assess and improve students' performance."
  values: ['yes', 'no', 'not_set']
  value_names:
   - 'Yes'
   - 'No'
   - 'Not Set'
  default: 'not_set'
  preview: true

- id: amplifies_project
  name: 'Amplifies Project'
  description: 'Amplifies the impact of a Frontline Program (FLP). Examples: Programs that use M&E data collected by CommCare. Programs that use CommCare data to make programmatic decisions.'
  values: ['yes', 'no', 'not_set']
  value_names:
   - 'Yes'
   - 'No'
   - 'Not Set'
  default: 'not_set'
  preview: true

- id: use_grid_menus
  name: Use Menu Grids
  description: Display root menu as a grid instead of a list.
  widget: bool
  default: false
  since: "2.24"
  toggle: GRID_MENUS

- id: minimum_use_threshold
  name: 'Minimum Use Threshold'
  description: 'This field indicates the minimum number of forms in this application that a user should submit monthly in order to be considered using sufficiently to generate a WAM. The default value is 15. Please see <a href="https://confluence.dimagi.com/display/internal/WAMs+and+PAMs">confluence</a> or the data team for further clarification.'
  widget: number
  preview: true
  warning: 'The minimum use threshold must be between 1 and 100'
  min_value: 1
  max_value: 100

- id: comment
  name: 'Comment'
  description: >
    A comment to document or explain this application for other app builders or maintainers.
  default: ''
  widget: textarea
