- name: "Auto Update Frequency"
  description: "How often CommCare mobile should attempt to check for a new, released application version."
  id: "cc-autoup-freq"
  values: ["freq-never", "freq-daily", "freq-weekly"]
  value_names: ["Never", "Daily", "Weekly"]
  default: "freq-never"
  values_txt: "After login, the application will look at the profile's defined reference for the authoritative location of the newest version. This check will occur with some periodicity since the last successful check based on this property. freq-never disables the automatic check."
  since: "1.3"
  force: true

- disabled: true
  name: "Purge Frequency"
  description: "How often the phone should attempt to purge any cached storage which may have expired"
  id: "purge-freq"
  values: ["0", "1", "7", "15", "31"]
  value_names: ["Whenever Possible", "Daily", "Once a Week", "Twice a Month", "Once a Month"]
  default: "0"
  values_txt: "Any positive integer. Represents period of purging in days."
  force: true

- name: "Days for Review"
  description: "Amount of time previously submitted forms remain accessible in the CommCare app."
  id: "cc-days-form-retain"
  values: ["1", "7",  "31", "92", "365", "-1"]
  value_names: ["Just One Day", "One Week", "One Month", "Three Months", "One Year", "Forms are Never Removed"]
  requires: "{features.sense}='false'"
  default: "-1"
  values_txt: "Any positive integer. Represents period of purging in days." 
  since: "2.8"
  force: true

- name: "Logging Enabled"
  description: "Whether logging of incidents should be activated on the client."
  id: "logenabled"
  values: ["Enabled", "Disabled"]
  value_names: ["Enabled", "Disabled"]
  default: "Enabled"
  group: "log"
  force: true

- name: "Weekly Log Sending Frequency"
  description: "What kind of log transmission the phone should attempt on a weekly basis (submitted to PostURL)"
  id: "log_prop_weekly"
  requires_txt: "Requires logging to be Enabled"
  requires: "{properties.logenabled}='Enabled'"
  commcare_default: "log_never"
  default: "log_short"
  values: ["log_never", "log_short", "log_full"]
  value_names: ["Never", "Short", "Full"]
  group: "log"
  force: true

- name: "Daily Log Sending Frequency"
  description: "What kind of log transmission the phone should attempt on a daily basis (submitted to PostURL)"
  id: "log_prop_daily"
  requires_txt: "Logging to be Enabled"
  default: "log_never"
  requires: "{properties.logenabled}='Enabled'"
  values: ["log_never", "log_short", "log_full"]
  value_names: ["Never", "Short", "Full"]
  group: "log"
  force: true

- name: "Send Data"
  description: "Whether or not the phone collects, saves, and sends data."
  id: "cc-send-procedure"
  default: "cc-send-http"
  values: ["cc-send-http", "cc-send-none"]
  "//values": ["cc-send-file"]
  value_names: ["Yes", "No (NOT RECOMMENDED)"]
  "//value_names": ["Save to the File System"]
  force: true

- name: "Password Format"
  description: "Determines whether phone keys will type letters or numbers by default when typing in the password field."
  id: "password_format"
  values: ["a", "n"]
  value_names: ["Alphanumeric", "Numeric"]
  default: "a"
  force: true

- name: "CommCare Home Screen Logo"
  description: "Choose an image to replace the default CommCare Home Screen logo"
  id: "logo_android_home"
  widget: "image_uploader"
  privilege: "commcare_logo_uploader"
  supports_linked_app: true
  force: true

- name: "Login Logo"
  description: "Upload a file to serve as a login logo on Android phones"
  id: "logo_android_login"
  widget: "image_uploader"
  privilege: "commcare_logo_uploader"
  supports_linked_app: true
  force: true

- name: "Demo Logo"
  description: "Upload a file to serve as a demo logo on Android phones"
  id: "logo_android_demo"
  widget: "image_uploader"
  privilege: "commcare_logo_uploader"
  supports_linked_app: true
  force: true

- disabled: true
  name: "Server User Registration"
  description: "Whether users registered on the phone need to be registered with the submission server."
  id: "user_reg_server"
  values: ["required", "skip"]
  value_names: ["Required", "Skip"]
  values_txt: "Set to skip if your deployment does not require users to register with the server. Note that this will likely result in OTA Restore and other features being unavailable."
  default: "required"
  force: true

- name: "Sync Mode"
  description: "Determines if the server automatically attempts to send data to the phone (Two-Way), or only attempt to send data on demand (Push Only); projects using Case Sharing should choose Two-Way. If set to Push Only, the Auto-Sync Frequency and Unsynced Time Limit settings will have no effect."
  id: "server-tether"
  values: ["push-only", "sync"]
  value_names: ["Push Only", "Two-Way Sync"]
  default: "push-only"
  requires: "{hq.case_sharing}=false"
  contingent_default: [{"condition": "{hq.case_sharing}=true", "value": "sync"}]
  force: true

- name: "Auto-Sync Frequency"
  description: "Automatically trigger a two-way sync on a regular schedule"
  id: "cc-autosync-freq"
  values: ["freq-never", "freq-daily", "freq-weekly"]
  value_names: [disabled, "Daily","Weekly"]
  default: "freq-never"
  values_txt: "When auto-sync is enabled CommCare will attempt to submit forms and synchronize the user's data after logging in with the frequency chosen."
  since: "2.0"
  force: true

- disabled: true
  name: "OTA Restore Tolerance"
  description: "Whether OTA Restore is tolerant of failures, ambiguity, duplicate registrations, etc (and proceeds as best it can), or whether it fails immediately in these cases."
  id: "restore-tolerance"
  values: ["strict", "loose"]
  value_names: ["Strict", "Loose"]
  default: "loose"
  force: true

- name: "Form Entry Style"
  description: "What user interface style should be used during form entry."
  id: "ViewStyle"
  values: ["v_chatterbox","v_singlequestionscreen"]
  value_names: ["Multiple Questions per Screen", "One Question per Screen"]
  values_txt: "Multiple Questions per Screen displays a running list of questions on the screen at the same time. One Question per Screen displays each question independently. Note: OQPS does not support some features"
  default: "v_chatterbox"
  force: true

- disabled: true
  id: "users"
  type: "features"
  name: "No Users Mode"
  description: "Whether to show the user login screen"
  values: ["true", "false"]
  value_names: ["Off", "On"]
  default: "true"
  group: "sense"
  widget: "bool"
  force: true

- id: "sense"
  type: "features"
  name: "CommCare Sense"
  description: "Configure for low-literate users, J2ME only"
  values: ["true", "false"]
  value_names: ["Yes", "No"]
  default: "false"
  group: "sense"
  widget: "bool"
  force: true

- id: "cc-user-mode"
  name: "User Login Mode"
  values: ["cc-u-normal", "cc-u-auto"]
  value_names: ["Normal", "Auto-login"]
  default: "cc-u-normal"
  commcare_default: "<-- having this property be different from 'default' forces 'cc-user-mode' to show up in the profile file"
  "//contingent_default": [{"condition": "{features.sense}='true'", "value": "cc-u-auto"}]
  description: "In normal mode, users log in each time with their username and password. In auto-login mode, once a user (not the 'admin' or 'demo' users) has logged in, the application will start up with that user already logged in."
  group: "sense"
  since: "1.3"
  force: true

- name: "Item Selection Mode"
  description: "Whether form entry is optimized for speed, or for new users."
  id: "cc-entry-mode"
  requires: "{features.sense}='false'"
  values: ["cc-entry-quick", "cc-entry-review"]
  value_names: ["Normal Scrolling", "Numeric Selection"]
  values_txt: "Numeric Selection mode will display information about questions for longer and require more input from the user. Normal Scrolling will proceed to the next question whenever enough information is provided."
  default: "cc-entry-quick"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "cc-entry-review"}]
  group: "sense"
  force: true

- name: "Send Forms Mode"
  description: "How Send All Unsent functionality is presented to the user"
  id: "cc-send-unsent"
  requires: "{features.sense}='false'"
  values: ["cc-su-auto", "cc-su-man"]
  value_names: ["Automatic", "Manual"]
  values_txt: "If automatic is enabled, forms will attempt to send on their own without intervention from the user. If manual is enabled, the user must manually decide when to attempt to send forms."
  default: "cc-su-auto"
  commcare_default: "cc-su-man"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "cc-su-auto"}]
  group: "sense"
  force: true

- name: "Extra Key Action"
  description: "What the 'Extra Key' (# on Nokia Phones) does when pressed"
  id: "extra_key_action"
  requires: "{features.sense}='false'"
  values: ["cycle", "audio"]
  value_names: ["Languages", "Audio"]
  values_txt: "Language cycles through any available translations. Audio plays the question's audio if available. NOTE: If audio is selected, a question's audio will not be played by default when the question is displayed."
  default: "audio"
  commcare_default: "cycle"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "audio"}]
  group: "sense"
  force: true

- disabled: true
  name: "Loose Media Mode"
  description: "Whether CommCare should search for alternative formats of incompatible media files."
  id: "loose_media"
  values: ["yes", "no"]
  value_names: ["Yes", "No"]
  default: "no"
  values_txt: "When loose media mode is set to yes, CommCare will search for alternative media formats for any media that it cannot play. If CommCare attempts to play a file at jr://file/media/prompt_one.mp3 and mp3 files are not supported, the media directory will be searched for other files named prompt_one with alternative extensions which may be supported, for instance prompt_one.wav, and play that instead."
  since: "1.3"
  force: true

# If cc-content-valid=yes it means the content has already been validated and should not be validated againmenu_
- name: "Multimedia Validation"
  description: "Whether CommCare should validate that all external multimedia is installed before letting the user run the app."
  id: "cc-content-valid"
  values: ["yes", "no"]
  value_names: ["No Validation", "Validate Multimedia"]
  default: "yes"
  values_txt: "If multimedia validation is enabled, CommCare will perform an additional check after installing your app to ensure that all of your multimedia is present on the phone before allowing the app to run. It is recommended for deployment, but will make your app unable to run if multimedia is enabled."
  since: "2.0"
  force: true

- name: "Unsent Form Limit"
  description: "Number of unsent forms on phone before triggering warning text"
  id: "unsent-number-limit"
  values: ["5", "10", "20", "40", "80", "160"]
  value_names: ["5", "10", "20", "40", "80", "160"]
  default: "5"
  values_txt: "When the phone has this number of unsynced forms stored locally CommCare will trigger a warning"
  since: "2.1"
  force: true

- name: "Unsynced Time Limit"
  description: "Days allowed without syncing before triggering a warning"
  id: "unsent-time-limit"
  values: ["-1", "1", "5", "7", "14", "30"]
  value_names: ["Never", "1 Day", "5 Days", "One Week", "Two Weeks", "One Month"]
  default: "5"
  values_txt: "When this many days have passed without the user syncing CommCare will trigger a warning"
  since: "2.4"
  force: true

- name: "Login Buttons"
  description: "Choose to label the login buttons with Icons or Text"
  id: "cc-login-images"
  values: ["Yes", "No"]
  value_names: ["Icons", "Text"]
  default: "No"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "Yes"}]
  values_txt: "This value will set whether the login screen uses customizable icons for login and demo mode options or uses the standard buttons with labels."
  since: "2.8"
  force: true

- name: "Saved Forms"
  description: "Choose whether or not mobile workers can view previously submitted forms."
  id: "cc-show-saved"
  values: ["yes", "no"]
  value_names: ["Enable", "Disable"]
  default: "no"
  commcare_default: "yes"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "no"}]
  values_txt: "This will show or hide the 'Saved' button on the CommCare ODK home screen. Turning this off will prevent users from saving forms locally."
  since: "2.11"
  force: true

- name: "Incomplete Forms"
  description: "Choose whether or not to display the 'Incomplete' button on the ODK home screen"
  id: "cc-show-incomplete"
  values: ["yes", "no"]
  value_names: ["Enable", "Disable"]
  default: "no"
  commcare_default: "yes"
  contingent_default: [{"condition": "{features.sense}='true'", "value": "no"}]
  values_txt: "This will show or hide the 'Incomplete' button on the CommCare ODK home screen. Turning this off will prevent users from saving incomplete forms."
  since: "2.11"
  force: true

- name: "Auto-Resize Images"
  description: "Automatically resizes images within forms. Follow 
  <a href='https://confluence.dimagi.com/display/commcarepublic/Auto-Resize+Images+on+Android'>
  the instructions here</a> to determine which value to use."
  id: "cc-resize-images"
  values: ["full", "half", "width", "none"]
  value_names: ["Full Resize", "Half Resize", "Horizontal Resize","None"]
  default: "none"
  values_txt: "This will determine how images you select for your questions will be resized to fit the screen. Horizontal will stretch/compress the image to fit perfectly horizontally while scaling to height to maintain the aspect ratio. Full Resize will try to be clever and find the ideal vertical/horizontal scaling for the screen. Half Resize will do the same but with half the area."
  since: "2.11"
  force: true

- name: "Fuzzy Search"
  description: "Whether searches on the phone will match similar strings. IE: 'Jhon' will match 'John'"
  id: "cc-fuzzy-search-enabled"
  values: ["yes", "no"]
  value_names: ["Yes", "No"]
  default: "yes"
  disabled_default: "no"
  values_txt: "Whether searches can match similar strings"
  since: "2.15"
  force: true

- name: "Log Case Detail Views"
  description: "Whether to log each time a user views case details. May reduce mobile performance."
  id: "cc-log-entity-detail-enabled"
  widget: bool
  default: false
  since: "2.24"
  force: true

- name: "Login Duration"
  description: "Length of time after which you will be logged out automatically"
  id: "cc-login-duration-seconds"
  values:      [   "86400",    "43200",   "28800",    "7200",   "3600",       "1800",        "900"]
  value_names: ["24 hours", "12 hours", "8 hours", "2 hours", "1 hour", "30 minutes", "15 minutes"]
  default: "86400"
  values_txt: "This will set the amount of time you will remain logged in before automatically being logged out."
  since: "2.21"
  force: true

- name: "Image Compatibility on Multiple Devices"
  description: "When a value is selected, this feature controls the display size of any user-provided image such
  that it will be consistent with the size of the original image file, and consistent across devices. Follow 
  <a href='https://confluence.dimagi.com/display/commcarepublic/Image+Sizing+with+Multiple+Android+Device+Models'>
  the instructions here</a> to determine which value to use."
  id: "cc-inflation-target-density"
  values: ["120", "160", "240", "320", "480", "640", "none"]
  value_names: ["Low Density", "Medium Density", "High Density", "X-High Density", "XX-High Density", "XXX-High Density", "None"]
  default: "none"
  since: "2.24"
  force: true
