- id: application_version
  name: "App Version"
  description: ""
  values: ["1.0", "2.0"]
  value_names: ["1.x", "2.x"]
  default: "2.0"
  disabled: true
  disabled_txt: "We suggest moving to CommCare 2.0 and above, unless your project is using referrals"

- id: build_spec
  name: "CommCare Version"
  description: 'We frequently release new versions of CommCare Mobile. Use the latest version to take advantage of new features and bug fixes. Note that if you are using CommCare for Android you must also update your version of CommCare from the Google Play Store.'
  widget: build_spec
  # this depends on builds are available, and on application_version
  # values, value_names, and default are magically set elsewhere
  # the build_spec widget depends on application_version coming before it in
  # this file

- id: use_j2me_endpoint
  name: "Send Data Over HTTP"
  description: "When you select this box, your data will no longer be encrypted.  Because of changes regarding Java phone security certificates, it will be necessary to send data over HTTP to continue sending data to CommCare."
  default: false
  widget: "bool"
  force: true

- id: platform
  name: "Java Phone Platform"
  values: ['nokia/s40', 'nokia/s60', 'winmo', 'generic']
  value_names: ['Nokia S40 (default)', 'Nokia S60', 'WinMo', 'Generic']
  default: 'nokia/s40'

- id: text_input
  name: "Text Input"
  widget: text_input
  values: ['roman', 'native', 'custom-keys', 'qwerty']
  value_names: [Roman, Native (International), Custom Keys, Full Keyboard]
  default: roman
  since: {qwerty: '2.6', 'custom-keys': '1.3'}
  requires: "{hq.platform}='nokia/s40'||{hq.platform}='nokia/s60'"

- id: practice_mobile_worker_id
  name: 'Practice Mobile Worker'
  widget: select
  since: '2.26'
  privilege: 'practice_mobile_workers'
  description: "Select the mobile worker to use as a practice user for this application"

# RemoteApp Only
- id: profile_url
  name: "Profile URL"
  requires: "{$parent.doc_type}='RemoteApp'"
  hide_if_not_enabled: true
  widget: text

- id: manage_urls
  name: "Auto-manage URLs"
  requires: "{$parent.doc_type}='RemoteApp'"
  hide_if_not_enabled: true
  widget: bool
  default: false


# Application only
- id: custom_base_url
  name: "Custom Base URL"
  description: 'Use a different base URL for all app URLs. This makes the phone send forms, sync and look for updates from a differnent URL. Main use case is to allow migrating ICDS to a new cluster.'
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  widget: text
  toggle: CUSTOM_APP_BASE_URL

- id: case_sharing
  name: "Case Sharing"
  description: 'Allow mobile workers in the same case sharing group to share case lists.  Read more on the <a href="https://help.commcarehq.org/display/commcarepublic/Case+Sharing">Help Site</a>'
  description_format: html
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  since: "2.0"

- id: cloudcare_enabled
  name: "Web App"
  description: 'Allow mobile workers to access the web-based version of your application. Read more on the <a href="https://help.commcarehq.org/display/commcarepublic/Using+Web+Apps">Help Site</a>'
  description_format: html
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  since: "2.0"
  permission: "cloudcare"

- id: anonymous_cloudcare_enabled
  name: "Anonymous Usage"
  description: 'Allow visitors to use this application without a login.'
  description_format: html
  widget: share_link
  default: false
  requires: "{$parent.doc_type}='Application'"
  hide_if_not_enabled: true
  since: "2.0"
  permission: "cloudcare"
  toggle: ANONYMOUS_WEB_APPS_USAGE

- id: use_custom_suite
  name: "Custom Suite File"
  widget: bool
  default: false
  requires: "{$parent.doc_type}='Application'"
  disabled: true

- id: custom_suite
  name: "Custom Suite"
  widget: textarea
  requires: "{$parent.doc_type}='Application'"
  disabled: true

- id: admin_password
  name: "Admin Password"
  description: Must correspond to the password format specified below.
  widget: password
  hide_if_not_enabled: true

- id: secure_submissions
  name: "Use Secure Submissions"
  widget: bool
  default: false
  since: '2.8'
  preview: true
  disable_if_true: true

- id: translation_strategy
  name: 'Translations Strategy'
  values: ['dump-known', 'select-known', 'simple']
  value_names:
   - 'Version 1 translations (old)'
   - 'Version 2 translations (recommended)'
   - 'Simple (FOR TESTING ONLY: crashes with any unrecognized user-defined translations)'
  default: 'select-known'
  requires: "{$parent.doc_type}='Application'"
  preview: true
  disabled: true
  disabled_txt: Oops! This setting has been discontinued. We recommend you change this setting to Version 2, and it will no longer appear on your settings page.

- id: auto_gps_capture
  name: 'Auto Capture Location<br />(all forms)'
  description: >
    On CommCare Android, have this form automatically capture the user's current geo-location.
  widget: bool
  default: false
  since: '2.14'

- id: use_grid_menus
  name: Modules Menu Display
  description: Display root menu as a list or grid. Read more on the <a target="_blank" href="https://help.commcarehq.org/display/commcarepublic/Grid+View+for+Form+and+Module+Screens">Help Site</a>.
  values: [false, true]
  value_names: ['List', 'Grid']
  default: false
  since: "2.24"

- id: grid_form_menus
  name: Forms Menu Display
  description: Configure form menus display. For per-module option turn on grid view for the form's menu in a module under module's settings page. Read more on the <a target="_blank" href="https://help.commcarehq.org/display/commcarepublic/Grid+View+for+Form+and+Module+Screens">Help Site</a>.
  values: ['none', 'all', 'some']
  value_names: ['List', 'Grid', 'Enable Menu Display Setting Per-Module']
  default: 'none'
  since: '2.24'

- id: mobile_ucr_sync_interval
  name: Mobile Reports Update Frequency
  description: Minimum duration between updates to mobile report data (hours).
  toggle: MOBILE_UCR
  values: ['none', '0', '1', '2', '4', '6', '8', '12', '24']
  value_names: ['Use project level setting', 'Update on every sync', '1 hour', '2 hours', '4 hours', '6 hours', '8 hours', '12 hours', '24 hours']
  default: 'none'

- id: mobile_ucr_restore_version
  name: Mobile UCR Restore Version
  description: Version of mobile UCRs to use. Read more on the  <a target="_blank" href="https://help.commcarehq.org/display/ccinternal/Moving+to+Mobile+UCR+V2">Help Site</a>
  toggle: MOBILE_UCR
  values: ['1.0', '1.5', '2.0']
  value_names: ['1.0', '1.5', '2.0']
  default: '1.0'
