postgres:
  image: dimagi/docker-postgresql
  environment:
    POSTGRES_USER: commcarehq
    POSTGRES_PASSWORD: commcarehq
  labels:
    commcare.name: "postgres"
  expose:
    - "5432"

couch:
  image: klaemo/couchdb:latest
  labels:
    commcare.name: "couch"
  expose:
    - "5984"

redis:
  image: redis
  labels:
    commcare.name: "redis"
  expose:
    - "6379"

elasticsearch:
  build: ../dockerfiles
  dockerfile: Dockerfile_es
  environment:
    ES_JAVA_OPTS: "-Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
  labels:
    commcare.name: "elastic"
  expose:
    - "9200"

elasticsearch_no_head:
  image: elasticsearch:1.7.4
  environment:
    ES_JAVA_OPTS: "-Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
  labels:
    commcare.name: "elastic"
  expose:
    - "9200"

web:
  build: ../../
  dockerfile: ./docker/dockerfiles/Dockerfile_commcarehq
  working_dir: /mnt
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - ../../:/mnt
  expose:
    - "8000"
  environment:
    PYTHONUSERBASE: /vendor
  labels:
    commcare.name: "web"

kafka:
  image: spotify/kafka
  environment:
    ADVERTISED_PORT: 9092
  expose:
    - "2181"
    - "9092"
  labels:
    commcare.name: "kafka"

riakcs:
  image: millerdev/riak-cs
  labels:
    commcare.name: "riakcs"
  expose:
    - "8080"
    - "8098"
